### ISSUE TITLE
[BUG] Importing utilipy triggers a "No module named 'ipykernel' " error ... the first time only ?

### ISSUE THREAD

**Issue by fpavogt** [nstarman/utilipy#18] opened 2020-12-11 10:39 UTC
### Description
Hello! I landed here after reading this excellent [article](https://utilipy.readthedocs.io/en/latest/examples/making-decorators.html). I'm currently working on a case where I need a decorator to properly document what the wrapper is doing (i.e. with respect to new kwargs). 

I pip-installed utilipy v1.0.1 without issue. But when I `import utilipy` from an `ipython` shell, I get a:

`ModuleNotFoundError: No module named 'ipykernel'` error.

### Expected behavior
Doing an `import utilipy` inside a `python` shell works fine. I was expecting the same to be true in an `ipython shell` ?

### Actual behavior
`import utilipy` leads to the following error message: 
```
/Users/redacted/opt/miniconda3/envs/redacted/lib/python3.8/site-packages/utilipy/utils/pickle.py:39: UserWarning: can't import dill. Will only use pickle.
  warnings.warn("can't import dill. Will only use pickle.")
set autoreload to 1
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-695b268aa64f> in <module>
----> 1 import utilipy

~/opt/miniconda3/envs/dvas/lib/python3.8/site-packages/utilipy/__init__.py in <module>
    100 
    101 # import packages into top-level namespace
--> 102 from . import (  # noqa
    103     astro,
    104     constants,

~/opt/miniconda3/envs/dvas/lib/python3.8/site-packages/utilipy/ipython/__init__.py in <module>
    136     InteractiveShell.ast_node_interactivity = "all"
    137 
--> 138     configure_matplotlib(backend="inline", figure_format="retina")
    139 
    140 

~/opt/miniconda3/envs/dvas/lib/python3.8/site-packages/utilipy/ipython/plot.py in configure_matplotlib(backend, figure_format)
     68     try:
     69         # set matplotlib backend
---> 70         get_ipython().magic(f"matplotlib {backend}")
     71 
     72     except UnknownBackend:

~/opt/miniconda3/envs/dvas/lib/python3.8/site-packages/IPython/core/interactiveshell.py in magic(self, arg_s)
   2412         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2413         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2414         return self.run_line_magic(magic_name, magic_arg_s, _stack_depth=2)
   2415 
   2416     #-------------------------------------------------------------------------

~/opt/miniconda3/envs/dvas/lib/python3.8/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2324                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2325             with self.builtin_trap:
-> 2326                 result = fn(*args, **kwargs)
   2327             return result
   2328 

<decorator-gen-101> in matplotlib(self, line)

~/opt/miniconda3/envs/dvas/lib/python3.8/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

~/opt/miniconda3/envs/dvas/lib/python3.8/site-packages/IPython/core/magics/pylab.py in matplotlib(self, line)
     97             print("Available matplotlib backends: %s" % backends_list)
     98         else:
---> 99             gui, backend = self.shell.enable_matplotlib(args.gui.lower() if isinstance(args.gui, str) else args.gui)
    100             self._show_matplotlib_backend(args.gui, backend)
    101 

~/opt/miniconda3/envs/dvas/lib/python3.8/site-packages/IPython/core/interactiveshell.py in enable_matplotlib(self, gui)
   3429                 gui, backend = pt.find_gui_and_backend(self.pylab_gui_select)
   3430 
-> 3431         pt.activate_matplotlib(backend)
   3432         pt.configure_inline_support(self, backend)
   3433 

~/opt/miniconda3/envs/dvas/lib/python3.8/site-packages/IPython/core/pylabtools.py in activate_matplotlib(backend)
    318     # when this function runs.
    319     # So avoid needing matplotlib attribute-lookup to access pyplot.
--> 320     from matplotlib import pyplot as plt
    321 
    322     plt.switch_backend(backend)

~/opt/miniconda3/envs/dvas/lib/python3.8/site-packages/matplotlib/pyplot.py in <module>
   2280     dict.__setitem__(rcParams, "backend", rcsetup._auto_backend_sentinel)
   2281 # Set up the backend.
-> 2282 switch_backend(rcParams["backend"])
   2283 
   2284 # Just to be safe.  Interactive mode can be turned on without

~/opt/miniconda3/envs/dvas/lib/python3.8/site-packages/matplotlib/pyplot.py in switch_backend(newbackend)
    219         else "matplotlib.backends.backend_{}".format(newbackend.lower()))
    220 
--> 221     backend_mod = importlib.import_module(backend_name)
    222     Backend = type(
    223         "Backend", (matplotlib.backends._Backend,), vars(backend_mod))

~/opt/miniconda3/envs/dvas/lib/python3.8/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

ModuleNotFoundError: No module named 'ipykernel'
```

Funny enough, if I then try it again, I get no errors at all. Any idea what is going on ?

**Side question:** in my code, I just need utilipy to fix a decorator, and intend to to a `from utilipy.utils.functools import wraps as utilipy_wraps` (which behaves as described above). I don't actually use astropy in the project. Why all the checks on ipython and matplotlib ? 

### Steps to Reproduce
1.  Launch an ipython shell
2.  `import utilipy` (-> throws error)
3.  `import utilipy` (-> succeeds)

### System Details
macOS-10.15.7-x86_64-i386-64bit
Python 3.8.2 (default, Mar 26 2020, 10:43:30) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
astropy 4.2
astroquery not installed
Matplotlib 3.2.2
Numpy 1.18.5
Scipy 1.5.0

### Checklist

- [x] Check out our [contributing guidelines](https://github.com/astropy/astropy/blob/master/CONTRIBUTING.md).
- [x] Check out our [code of conduct](https://github.com/astropy/astropy/blob/master/CODE_OF_CONDUCT.md).
- [x] Search the GitHub repository to see if a similar issue has already been posted. If a similar issue is closed, have a quick look to see if you are satisfied by the resolution. If not please go ahead and open an issue!
- [ ] Please check that the development version still produces the same bug. You can install development version with ``pip install git+https://github.com/astropy/astropy`` command.

**Comment by nstarman** [comment] 2020-12-14 04:14
Hi @fpavogt. I'm glad you liked the article on decorators. Thanks for finding this bug. I'm having some trouble reproducing it on my ipython kernel. 

Ive opened #20 to try to address this. Basically, since you don't need `ipython`, it shouldn't be imported right away. If you need this right away, pip can install from a specific branch `pip install git https://github.com/user/repo.git@branch`. This should be fixed soon, and I've been meaning to push v1.1. I'll either do that or a bug fix for v1.0.2

**Comment by nstarman** [comment] 2020-12-14 05:09
> Any idea what is going on ?

I think that it's the matplotlib kernel switching to `Agg` or something.

> I don't actually use astropy in the project. Why all the checks on ipython and matplotlib ?

A fair bit of functions that you don't use are astropy dependent. The ipython and matplotlib checks are for the `ipython` sub-package. The latter should be fixed (#20) by only importing that on an as-needed basis, but the astropy integrations are tighter and cannot be separated.

**Comment by fpavogt** [comment] 2020-12-14 16:06
Hi @nstarman. Thanks for the prompt feedback and fix ! I just pip-installed from your master branch, and I confirm that the bug seems to be gone now. I can import the module with only the dill import warning (which is fine, since I don't have it installed). 

Fair enough for the astropy package. Down the line, I may need to dabble into its units sub-module, so maybe it was just a matter of time until it made into the list of the requirements anyway :)

**Comment by fpavogt** [comment] 2020-12-14 16:09
One follow-up question: do you have an ETA for the pip release of v1.1 ? We would not be able to use `utilipy` on our side until that occurs. We're not in any particular rush on that front, it's just to get an idea.

**Comment by nstarman** [comment] 2020-12-14 17:46
> One follow-up question: do you have an ETA for the pip release of v1.1 ?

Hopefully within the next few days. I switched over from a custom config file system to the Astropy one. As this is a breaking change, I need to do a version bump. I'm working on auto-release by tag (#21), so... soon.

**Closed** 2024-01-30 20:41 UTC
Labels: no-issue-activity
